M48
; DRILL file {KiCad (7.0.0)} date Wed Mar  8 18:54:57 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-03-08T18:54:57-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.300
%
G90
G05
T1
X143.524Y-107.832
X155.589Y-95.847
T2
X146.023Y-97.792
T0
M30
